import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {saveMemory,searchMemory,withdrawMemory,getMemory} from '../lib/shared-memory-engine';
import {processVectorJobs} from '../lib/memory-vector-index';
import {prepareRecall,acknowledgeRecall,recentRecall} from '../lib/shared-memory-recall';
import {proposeMemory,listCandidates,reviewCandidate,editCandidate} from '../lib/memory-candidates';
function database(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync('tools/fixtures/shared-memory-schema.sql','utf8'));return {sql,db:{prepare(text:string){const make=(args:any[]=[])=>({bind:(...v:any[])=>make(v),first:async()=>sql.prepare(text).get(...args)??null,all:async()=>({results:sql.prepare(text).all(...args)}),run:async()=>sql.prepare(text).run(...args)});return make();},async batch(statements:any[]){sql.exec('BEGIN');try{const r=[];for(const s of statements)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}} as any};}
const {db,sql}=database(),ledger=database();
const env={DB:db,EMBEDDING_ENABLED:'false',EMBEDDING_MODEL:'fixture-vector',EMBEDDING_URL:'https://fixture.invalid/vectors',EMBEDDING_DIMENSIONS:'3',EMBEDDING_INDEX_VERSION:'v1'};
const refs=[{conversation_id:'fictitious-source',message_id:'fictitious-original',quote:'虚构原话',created_at:null}];
const gift=await saveMemory(db,{body:'虚构案例：给广东朋友挑碧螺春甜点。',source:'isolated fiction',kind:'episode',occurred_at:null,details:{evidence:refs,participants:['fictional user','fictional Rowan']}});
const song=await saveMemory(db,{body:'虚构案例：Apple Music 特别的人已经成功播放。',source:'isolated fiction',kind:'episode',details:{evidence:refs}});
await saveMemory(db,{body:'虚构案例：Apple Music 特别的人在梦里播放。',source:'isolated fiction',kind:'dream'});
await saveMemory(db,{body:'不使用 emoji；语音用英文。',source:'isolated fiction',kind:'preference'});
const originalFetch=globalThis.fetch;let calls=0;
try{
 globalThis.fetch=async(_url,options)=>{calls++;const input=JSON.parse(String(options?.body)).input;let embedding=[0,0,1];if(/碧螺春|网友|伴手礼/.test(input))embedding=[1,0,0];else if(/Apple|分享歌曲/.test(input))embedding=[0,1,0];return Response.json({data:[{embedding}]});};
 await processVectorJobs(env);await searchMemory(env,{query:'网友伴手礼'});assert.equal(calls,0,'disabled must never transmit text');
 env.EMBEDDING_ENABLED='true';assert.equal((await processVectorJobs(env)).indexed,4);
 const count=calls;const matches=await searchMemory(env,{query:'之前给网友的伴手礼',kind:'episode'});
 assert.equal(calls,count+1,'retrieval only embeds query, never documents');assert.equal(matches.hits[0].id,gift.id);
 assert.equal(matches.hits[0].occurred_at,null);assert.equal(matches.hits[0].reason,'semantic_similarity');
 const batch=await prepareRecall(db,ledger.db,{query:'之前给网友的伴手礼',conversationId:'new-empty-chat',messageId:'m1'},new Date(),env);
 assert.ok(batch.memories.some(m=>m.id===gift.id&&m.reason==='related_history'));
 assert.ok(batch.memories.some(m=>m.reason==='standing_preference'));
 await acknowledgeRecall(ledger.db,{deliveryId:batch.deliveryId,conversationId:'new-empty-chat',messageId:'m1',turnId:'fixture-turn'});
 const repeat=await prepareRecall(db,ledger.db,{query:'还记得之前给网友的伴手礼吗',conversationId:'new-empty-chat',messageId:'m2'},new Date(),env);
 assert.ok(repeat.memories.some(m=>m.id===gift.id),'explicit follow-up bypasses cooldown');
 const unrelated=await prepareRecall(db,ledger.db,{query:'求解二次方程',recent:[{role:'user',content:'之前的伴手礼'}],conversationId:'fresh-unrelated',messageId:'m3'},new Date(),env);
 assert.ok(!unrelated.memories.some(m=>m.reason==='related_history'),'new unrelated topic must not inherit past topic');
 const music=await prepareRecall(db,ledger.db,{query:'那次终于播放的分享歌曲',conversationId:'fresh-song',messageId:'m4'},new Date(),env);
 assert.deepEqual(music.memories.filter(m=>m.reason==='related_history').map(m=>m.id),[song.id]);
 const debug=await recentRecall(ledger.db,'new-empty-chat',true);assert.equal(debug.items[0].context,batch.context);assert.ok(debug.items[0].diagnostics.candidates.some((m:any)=>m.id===gift.id&&m.reason==='selected'));
 await withdrawMemory(db,gift.id,'fictitious withdrawal');assert.equal(sql.prepare('SELECT count(*) AS n FROM memory_vectors WHERE memory_id=?').get(gift.id)?.n,0);
 assert.ok(!(await searchMemory(env,{query:'网友伴手礼',kind:'episode'})).hits.some(m=>m.id===gift.id));
 const updated=await saveMemory(db,{id:song.id,body:'虚构纠正：Apple Music 仍未播放成功。',source:'isolated fiction',kind:'episode',correction_reason:'test correction'},true);
 await processVectorJobs(env);assert.ok(!(await searchMemory(env,{query:'分享歌曲',kind:'episode'})).hits.some(m=>m.id===song.id));assert.equal((await getMemory(db,song.id)).active,0);
 env.EMBEDDING_INDEX_VERSION='v2';await processVectorJobs(env);assert.equal(sql.prepare('SELECT count(*) AS n FROM memory_vector_indexes').get()?.n,2,'rebuild uses distinct index version');
 globalThis.fetch=async()=>{throw new Error('offline')};const fallback=await prepareRecall(db,ledger.db,{query:'Apple Music',conversationId:'offline-new',messageId:'m5'},new Date(),env);
 assert.ok(fallback.memories.some(m=>m.reason==='standing_preference'));assert.ok(fallback.diagnostics.warnings.includes('embedding_unavailable_lexical_fallback'));
 const candidate=await proposeMemory(db,'owner',{body:'候选：只包含已核对原话的经历。',source:'isolated fixture',kind:'episode',details:{evidence:refs}});
 assert.equal(candidate.stored,false);assert.equal((await listCandidates(db,'other')).items.length,0);
 await assert.rejects(reviewCandidate(db,'other',{id:candidate.candidateId,action:'accept'},async()=>{}),/not_found/);
 await assert.rejects(reviewCandidate(db,'owner',{id:candidate.candidateId,action:'accept'},async()=>{throw Error('unverified')}));
 assert.equal((await listCandidates(db,'owner')).items.length,1);
 const accepted=await reviewCandidate(db,'owner',{id:candidate.candidateId,action:'accept'},async()=>refs);assert.equal(accepted?.status,'accepted');assert.equal((await listCandidates(db,'owner')).items.length,0);
 const editable=await proposeMemory(db,'owner',{body:'可修改候选',source:'fixture',kind:'episode',details:{evidence:[{...refs[0],message_id:'edit-source'}]}});
 const editPayload={body:'已核对后修改候选',source:'fixture',kind:'episode',occurred_at:null,details:{evidence:[{...refs[0],message_id:'edit-source'}]}};
 await editCandidate(db,'owner',editable.candidateId,editPayload);
 assert.equal((await listCandidates(db,'owner')).items.find((i:any)=>i.id===editable.candidateId).body,editPayload.body);
 await assert.rejects(reviewCandidate(db,'owner',{id:editable.candidateId,action:'accept'},async()=>{await editCandidate(db,'owner',editable.candidateId,{...editPayload,details:{...editPayload.details,summary:'concurrent change'}});}),/UNIQUE/);
 assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM memories WHERE source_id=?').get('candidate:'+editable.candidateId)?.n,0,'concurrent edit rolls back acceptance');
 const race=await proposeMemory(db,'owner',{body:'待核对的另一个候选',source:'fixture',kind:'episode',details:{evidence:[{...refs[0],message_id:'race-source'}]}});
 await assert.rejects(reviewCandidate(db,'owner',{id:race.candidateId,action:'accept'},async()=>{await reviewCandidate(db,'owner',{id:race.candidateId,action:'reject'},async()=>{});}),/candidate_not_pending/);
 assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM memories WHERE source_id=?').get('candidate:'+race.candidateId)?.n,0,'concurrent rejection cannot leave an active memory');
 console.log('PASS isolated hybrid fixtures: opt-in/privacy, async indexing, semantic candidate transport, standing preferences, unrelated rejection, follow-up cooldown, dreams, correction/withdrawal, model rebuild, failure fallback, exact traces and source-reviewed candidates. Mock vectors test plumbing, not embedding quality.');
}finally{globalThis.fetch=originalFetch;sql.close();ledger.sql.close();}
