import { memoryAdditionalContext } from '../lib/memory-transport';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { saveMemory, getMemory, withdrawMemory } from '../lib/shared-memory-engine';
import { prepareRecall, acknowledgeRecall, recentRecall, recallFeedback, RECALL_CHAR_BUDGET } from '../lib/shared-memory-recall';
function database(){const sqlite=new DatabaseSync(':memory:');return {sqlite,db:{prepare(sql:string){let values:unknown[]=[];return {bind(...args:unknown[]){values=args;return this;},async first(){return sqlite.prepare(sql).get(...values as any[])??null;},async all(){return {results:sqlite.prepare(sql).all(...values as any[])};},async run(){return sqlite.prepare(sql).run(...values as any[]);}};},async batch(statements:any[]){sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}} as any};}
const memory=database(),ledger=database();memory.sqlite.exec(readFileSync('tools/fixtures/shared-memory-schema.sql','utf8'));
const save=(body:string,kind='episode',extra={})=>saveMemory(memory.db,{body,kind,source:'fictional test only',...extra});
const prefs=await save('不用 emoji；语音仅用英文。','agreement');
const tea=await save('更喜欢茶本身，不喜欢甜点。','preference');
const swing=await save('虚构验收：在楼下秋千上通话。','episode',{occurred_at:'2026-10-01T20:00:00+08:00',details:{title:'虚构秋千通话',evidence:[{conversation_id:'fiction',message_id:'fixture',quote:'楼下秋千'}]}});
await save('虚构秋千梦境','dream');await save('秋千让我感到平静','reflection');
const prepare=(query:string,messageId=crypto.randomUUID(),recent:any[]=[])=>prepareRecall(memory.db,ledger.db,{query,conversationId:'fixture-chat',messageId,recent});
const first=await prepare('秋千');assert.equal(first.status,'prepared');assert.equal((await recentRecall(ledger.db)).items.length,0);
assert.deepEqual(new Set(first.memories.map(m=>m.id)),new Set([prefs.id,tea.id,swing.id]));
assert.ok(first.context.includes('2026-10-01T12:00:00.000Z'));assert.ok(first.context.length<=RECALL_CHAR_BUDGET);assert.ok(!first.context.includes('梦境'));
await assert.rejects(acknowledgeRecall(ledger.db,{deliveryId:first.deliveryId,conversationId:'other',messageId:first.messageId,turnId:'t1'}),/delivery_not_found/);
await acknowledgeRecall(ledger.db,{deliveryId:first.deliveryId,conversationId:'fixture-chat',messageId:first.messageId,turnId:'t1'});
assert.equal((await recentRecall(ledger.db)).items[0].context,first.context);
await assert.rejects(acknowledgeRecall(ledger.db,{deliveryId:first.deliveryId,conversationId:'fixture-chat',messageId:first.messageId,turnId:'t2'}),/delivery_turn_conflict/);
assert.equal((await prepare('unrelated')).memories.length,2);assert.equal((await prepare('秋千')).memories.length,2,'episodes cool down but standing preferences repeat');
await recallFeedback(ledger.db,{deliveryId:first.deliveryId,memoryId:tea.id,kind:'changed'},memory.db);
assert.ok(!(await prepare('茶')).memories.some(m=>m.id===tea.id));
assert.ok((await getMemory(memory.db,tea.id)).review);
const corrected=await saveMemory(memory.db,{id:tea.id,body:'现在可以接受少量甜点。',kind:'preference',source:tea.source,correction_reason:'虚构偏好纠正'},true);
assert.ok((await prepare('茶')).memories.some(m=>m.id===corrected.id),'a new corrected version is usable');
assert.ok(!(await prepare('茶')).memories.some(m=>m.id===tea.id));
assert.ok((await getMemory(memory.db,tea.id)).review);
await withdrawMemory(memory.db,prefs.id,'虚构撤回');assert.ok(!(await prepare('emoji')).memories.some(m=>m.id===prefs.id));
assert.equal((await getMemory(memory.db,prefs.id)).body,prefs.body);assert.ok((await getMemory(memory.db,prefs.id)).withdrawal);
assert.equal((await getMemory(memory.db,swing.id)).details.title,'虚构秋千通话');
await assert.rejects(saveMemory(memory.db,{id:prefs.id,body:'stale',kind:'agreement',source:'fixture',correction_reason:'stale'},true),/stale_version/);
const other=await prepareRecall(memory.db,ledger.db,{query:'再聊聊吧',recent:[{role:'user',content:'楼下秋千'}],conversationId:'another-chat',messageId:'context'});
assert.ok(other.memories.some(m=>m.id===swing.id));
const race=await Promise.all([prepare('秋千','same-message'),prepare('茶','same-message')]);assert.notEqual(race[0].deliveryId,race[1].deliveryId,'preparations have immutable distinct snapshots');
await withdrawMemory(memory.db,corrected.id,'test');await withdrawMemory(memory.db,swing.id,'test');
assert.equal((await prepare('不存在的旧事')).context,'');
const unknown=await save('日期未知的虚构星河事件');assert.equal((await getMemory(memory.db,unknown.id)).occurred_at,null);
console.log('PASS recall: standing preferences, episodes, context, cooldown, immutable receipts, changed/corrected, withdrawal, nonfacts, empty/unknown dates');

const longContext='茶与星河 🌙'.repeat(3000);const fragments=memoryAdditionalContext(longContext);
assert.equal(Object.keys(fragments).sort().map(k=>fragments[k].value).join(''),longContext);
assert.ok(Object.values(fragments).every(part=>Buffer.byteLength(part.value,'utf8')<=768));
console.log('PASS lossless bounded host fragments; disabled until deployed schema is verified');
